export enum MobileSectionType {
    HERO_BANNER = 1,
    SLIDER = 2,
    THUMBNAIL_DARK_BACKGROUND = 3,
    BANNER = 4,
    THUMBNAIL_LIGHT_BACKGROUND = 5,
    HERO_BANNER_THUMBNAIL_DESCRIPTION = 6,
    BANNER_DESCRIPTION = 7,
    WITHOUT_IMAGE = 8,
    NUMBER = 9,
}

export enum DesktopSectionType {
    HERO_BANNER = 1,
    SLIDER = 2,
    BANNER = 3,
    HERO_BANNER_THUMBNAIL_DESCRIPTION = 4,
    BANNER_DESCRIPTION = 5,
    NUMBER = 6,
    BANNER_DARK_BACKGROUND = 7,
    HERO_BANNER_BOTTOM_TEXT = 8,
}
